language: clojure
sudo: false
script: ./boot travis
branches:
  only:
    - master
    - kentnl
env:
  - UTRECHT_TEST_DB="utrecht_test"
services:
  - postgresql
before_script:
  - psql -c 'create database utrecht_test;' -U postgres
jdk:
  - oraclejdk8
#  - openjdk7 # tests fail - probably running out of memory or disk
# travis does not support any of these (yet):
#  - oraclejdk9
#  - openjdk8
#  - openjdk9
install:
  - curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
  - chmod 755 boot
  - ./boot installdeps
  - ./boot show -d
